apiDir: "../liferay-apps-headless-api/src/main/java"
apiPackagePath: "com.liferay.headless.apps"
application:
  baseURI: "/headless-apps"
  className: "HeadlessAppsApplication"
  name: "Liferay.Headless.Apps"
author: "Vitaliy Koshelenko"